apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnativepg
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: 'cloudnative-pg'
      version: '0.18.0'
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
  install:
    createNamespace: true 
    crds: CreateReplace
  upgrade:
    crds: CreateReplace