apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-repository
  namespace: default
spec:
  interval: 1m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: 'cert-manager'
      version: 'v1.11.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repository
        namespace: default
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace