apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/nginxinc/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: 'nginx-ingress'
      version: '0.17.1'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace