apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-2
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: 'ingress-nginx'
      version: '4.7.0'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
  install:
    createNamespace: true 
    crds: CreateReplace
  upgrade:
    crds: CreateReplace