#cloud-config
write_files:
  - content: |
      { lib, ... }: {
        networking = {
          dhcpcd.enable = lib.mkForce true;

          interfaces.enp7s0 = {
            useDHCP = true;
          };
        };
      }
    path: /etc/nixos/host.nix
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | NIXOS_IMPORT=/etc/nixos/host.nix PROVIDER=hetznercloud NIX_CHANNEL=nixos-unstable bash 2>&1 | tee /tmp/infect.log