#cloud-config
write_files:
  - content: |
      { lib, ... }: {
        systemd.services.network-addresses-enp7s0 = { after = [ "dhcpcd.service" ]; };
        networking = {
          interfaces.enp7s0 = {
            useDHCP = false;
            ipv4 = {
              addresses = [ { address = "${ip}"; prefixLength = 24; } ];
              routes = [ 
                { address = "10.69.100.1"; prefixLength = 32; } 
                { address = "10.69.100.0"; via="10.69.100.1"; prefixLength = 24; } 
              ];
            };
          };
        };
      }
    path: /etc/nixos/host.nix
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | NIXOS_IMPORT=/etc/nixos/host.nix PROVIDER=hetznercloud NIX_CHANNEL=nixos-unstable bash 2>&1 | tee /tmp/infect.log