name: Build docker images
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate docker image ID
        run: echo image_id=${{ env.REGISTRY }}/backend:${GITHUB_REF##*/}-$(date +%s) >> "$GITHUB_ENV"

      - name: Build docker image
        run: "./docker-build.sh ${{ env.image_id }}"

      - name: Print image ID
        run: echo ${{ env.image_id }}