name: build
on:
  status:
    state: success
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:      
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11-small
      
      - name: Deploy
        run: nix-shell --command "terraform output"